### ISSUE TITLE
Running POET estimator over all genes and subsetting to reference-specific genes later

### ISSUE THREAD

**Issue by ndejay** [rujinwang/EPIC#12]
Hello,

I am wondering if there is a way to speed up using a GWAS study with multiple data sets by running POET estimator over all genes and subsetting to reference-specific genes later

For example, in `Section 4.3` of the [vignette](https://htmlpreview.github.io/?https://github.com/rujinwang/EPIC/blob/master/vignettes/EPIC_vignette.html), one could:

1. Once per GWAS study, call `EPIC::calculate_POET_sw` after expanding `gtex.loc` to include all genes in `combine_gene_pval`
2. Once per expression reference, call `EPIC::get_gene_chisq` and subset to genes present in reference

However, I suspect this might distort the results, so I wanted to run this by you.  Would love to hear your thoughts!

Thanks!
Nic

**Comment by rujinwang** [comment]
Hi @ndejay , 
Yes you can expand to include all genes first and then subset to expression reference specific genes. But this would affect the POET estimators since the sliding window would include different gene sets. I wouldn't advise not to do this but please be cautious of false positive gene-chisq results. 

Best, 
Rujin
