### ISSUE TITLE
EPIC 2nd pruning and POET error

### ISSUE THREAD

**Issue by SKVirk27** [rujinwang/EPIC#9]
I have tried a lot to fix the errors but unable to get any resolution. Could you please suggest how to fix the errors.

I encountered my 1st error while performing
  maf <- 0.01
> #out_dir = "/path/to/plink_output"
> prunein_dir <- file.path(out_dir, paste0("prunein2", "_", trait), MAF)
> results_dir <- file.path("//Users/simranjitvirk/Downloads/SMR/results", trait)
> bfile_path <-"/Users/simranjitvirk/Downloads/SMR"
> plink_path <- "/Users/simranjitvirk/Downloads/SMR/plink_mac/plink"
> chr = 1
> if(!dir.exists(results_dir)){
+   dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)
+ }
> prunein_qc_snp_to_gene.chr <- second_pruning(prunein_snp_to_gene, plink_path, bfile_path, chr, prunein_dir)
Error in second_pruning(prunein_snp_to_gene, plink_path, bfile_path, chr,  : 
  Invalid MAF threshold! 
I had changed MAF threshold value but this error is still happening.   I tried to skip 2nd pruening and used LD pruening results and tried to perform

  inter_dir <- file.path("/Users/simranjitvirk/Downloads/SMR", trait)
> error=utils::recover
> calculate_POET_sw(genotype = X_ref.Demo, gene_pval = prunein_gene_pval, 
+                   gene.loc = scRNA.loc, # For scRNA-seq data, specify gene.loc = scRNA.loc, which is returned by function process_scRNA()
+                   chr = chr, type = "POET", inter_dir = inter_dir)

Error in seq.default(1, (length(gene_pval) - sliding_size + 1), sliding_step) : 
  wrong sign in 'by' argument
>  Please help me fix this errors. Also it will be helpful if you can suggest from where i can get X_ref of eur population for all chromosomes as it is very memory consuming if I tried on my system or carbonate. You can suggest me sources or packages. Any response will be appreciated. Thank you

**Comment by rujinwang** [comment]
Hi @SKVirk27 
Thanks for your interest in EPIC. 

1. MAF threshold: By default, EPIC use MAF=1%. You don't need to specify MAF. If you are interested in custom MAFs, make sure 0<YOUR_CUSTOM_MAF<1, otherwise you would get errors "Invalid MAF threshold!". Also, please specify your custom MAF in `second_pruning(prunein_snp_to_gene, maf_thres = YOUR_CUSTOM_MAF, plink_path, bfile_path, chr, prunein_dir)`
2. calculate_POET_sw: Please make sure `length(prunein_gene_pval)>10`. Additionlly, `X_ref.Demo` is a toy dataset of chr2. Most likely your `prunein_gene_pval` is not of chr2. Please use your own `X_ref`. 
3. X_ref: The bim file for the 1000 Genomes Project European population is [public](https://ctg.cncr.nl/software/magma) available. Please read through [section 4.1](https://htmlpreview.github.io/?https://github.com/rujinwang/EPIC/blob/master/vignettes/EPIC_vignette.html#chi2-test-for-prune-in-common-variants) carefully on how to construct `X_ref`

Thanks. 

Rujin

**Comment by SKVirk27** [comment]
Thank you for response, I really appreciate. I am not getting maf_threshold error after putting maf_threshold value like "second_pruning(prunein_snp_to_gene, maf_thres = YOUR_CUSTOM_MAF, plink_path, bfile_path, chr, prunein_dir)" . I am only stuck in poet analysis. I created X_ref for chr1 from the eur data.  I am still getting error. please suggest how I can resolve it ? You are really doing a great job!. > # χ2 test for prune-in common variants
> X_ref=readRDS("/Users/simranjitvirk/Downloads/SMR/results/X_ref_chr1.rds")
> inter_dir <- file.path("/Users/simranjitvirk/Downloads/SMR", trait)
> chr=1
> calculate_POET_sw(genotype = X_ref, gene_pval = prunein_qc_snp_to_gene, 
+                   gene.loc = scRNA.loc, # For scRNA-seq data, specify gene.loc = scRNA.loc, which is returned by function process_scRNA()
+                   chr = chr, type = "POET", inter_dir = inter_dir)
Error in seq.default(1, (length(gene_pval) - sliding_size + 1), sliding_step) : 
  wrong sign in 'by' argument

**Comment by rujinwang** [comment]
Run the following code to check
```
gene.loc <- gene.loc[order(gene.loc$V2, gene.loc$V3, gene.loc$V4), ]
gene.loc <- gene.loc[which(gene.loc$V2==chr), ]

gene.loc <- gene.loc[which(!is.na(match(gene.loc$V1, names(gene_pval)))), ]
gene_pval <- gene_pval[match(gene.loc$V1, names(gene_pval))]
```

Most likely your `length(gene_pval) < 10`

Thanks,
Rujin

**Comment by SKVirk27** [comment]
Yes you are right the length(gen_pval) is less than 10. What should i do next?. Is there any way I can fix the sliding_step error. Shall i manually add steps according to the length of gene_pval? Thank you.

**Comment by rujinwang** [comment]
You can specify `sliding_size` in `calculate_POET_sw()`, which is set as `10` by default. You can make custom `sliding_size`  but ensure  `1 < sliding_size < length(gene_pval)`.  

calculate_POET_sw(genotype, gene_pval, gene.loc, chr, type, inter_dir, **sliding_size = 10**)

Rujin

**Comment by SKVirk27** [comment]
Thank you, I will try to perform analysis again because my length(gene_pval)=1 for chr1.

I have few doubts, I started with  big summary stats file, after LD pruning I left with approx. 31002 genes and when I read  prunein_gene_pval ,  I had left with only 44 genes with statistical value. Is it ok to get these numbers?

prunein_gene_pval <- read_in(gwas = gwas.formatted, snp_to_gene = prunein_qc_snp_to_gene),

2nd question

Shall I combine Xref file for all chromosomes and then do poet test . Is it make difference to perform analysis individually for each chromosome or combined.

You have a great experience in this area, so I appreciate if you can answer my question. Thank you so much again for your replies.


Your sincerely,
Simranjit Kaur Virk




On Apr 9, 2023, at 8:40 PM, Rujin Wang ***@***.***> wrote:

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.



You can specify sliding_size in calculate_POET_sw(), which is set as 10 by default. You can make custom sliding_size but ensure 1 < sliding_size < length(gene_pval).

calculate_POET_sw(genotype, gene_pval, gene.loc, chr, type, inter_dir, sliding_size = 10)

Rujin

**Comment by rujinwang** [comment]
Hi, 
It does not make any sense that gene number dropped from 31K to only 44. I would suggest you walk through every step in the tutorial and make sure the input data is correct / conforms to EPIC requirements. 

EPIC is designed to perform analysis chr by chr. Otherwise it would be extremely computational cumbersome. 

I will close this issue for now. Thanks. 

Rujin
